# Generated by Django 2.2.4 on 2019-08-23 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField()),
                ('jobtitle', models.CharField(max_length=128)),
                ('jobdescription', models.CharField(max_length=512)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('company', models.CharField(blank=True, default='Joogle, Inc', max_length=64)),
            ],
        ),
    ]
