# Generated by Django 2.2.4 on 2019-08-23 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20190823_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jobid',
            field=models.IntegerField(unique=True),
        ),
    ]
