# Generated by Django 2.2.4 on 2019-08-24 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobid', models.IntegerField()),
                ('jobtitle', models.CharField(max_length=128)),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('email', models.CharField(max_length=256, unique=True)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
